### ISSUE TITLE
Prevent scrolling when pressing with spacebar

### ISSUE THREAD

**Issue by giuseppeg** [danoc/clickable-box#23]
When focused by default buttons prevent scrolling when pressing `spacebar`. But clickable box is not https://github.com/danoc/clickable-box/blob/70621a9d5c574983ff32c6c14f8fccf7f1d9c955/src/index.jsx#L15

**Comment by danoc** [comment]
Thanks for the issue. Will get to it when I have time, but happy to accept a PR from anyone interested.

**Comment by danoc** [comment]
Thanks, @giuseppeg. Just merged and released.
