### ISSUE TITLE
Should the button have `cusor: pointer` or is that too opinionated?

### ISSUE THREAD

**Issue by danoc** [danoc/clickable-box#5]
**Resources:**
* https://ux.stackexchange.com/questions/105024/why-dont-button-html-elements-have-a-css-cursor-pointer-by-default
* https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b

**Comment by danoc** [comment]
Deciding to keep `cursor: pointer` since nearly all sites end up setting `cursor: pointer`—especially for buttons that look like text links.

**Comment by hidde** [comment]
Just to add a voice here: I think having `cursor: pointer` is opinionated, would vote for not having it to mimic default browser and OS behavior for buttons.

**Comment by danoc** [comment]
Thanks, @hidde — Going to re-open this.

I'm open to changing it but would like to find a solution that makes it easy for consumers to add `cursor: pointer` if they would like.

This is easy with a normal button and three lines of global CSS:

```
button {
  cursor: pointer;
}
```

It's a little less intuitive with `ClickableBox` since the element is usually a `span`. We could, however, add documentation that encourages users that want this behavior to add `[role="button"] { cursor: pointer }` to their global CSS.

What do you think?

**Comment by scottaohara** [comment]
People can add class names to it. Why not just let people do it that way?
