### ISSUE TITLE
invoke onClick with the event onKeyPress

### ISSUE THREAD

**Issue by giuseppeg** [danoc/clickable-box#7]
Hi there, I think that you should invoke `onClick` with the event`onKeyPress`

https://github.com/danoc/clickable-box/blob/9606d466af9a171f49a2d31637ae84b0c70d4806/src/index.jsx#L16-L20

**Comment by danoc** [comment]
Hi @giuseppeg, thanks for the comment.

Not sure if I understand. `onClick` is invoked with the `onKeyPress` event if the key is "Enter" or "Space." Is that what you'd expect?

**Comment by giuseppeg** [comment]
I mean you should call `onClick` with the `event` which is what happens on regular buttons

**Comment by giuseppeg** [comment]
the component should also allow to pass `onKeyPress` which will fire both `onKeyPress` and `onClick`. 
Something like this:

```jsx
onKeyPress = event => {
   const { onKeyPress, onClick } = this.props
   typeof onKeyPress == 'function' && onKeyPress(event)
   typeof onClick == 'function' && ['Enter', 'Space'].contains(event.key) && onClick(event)
}

render() {
  const { onClick, onKeyPress, ...rest } = this.props
  return <Component onClick={onClick} onKeyPress={this.onKeyPress} {...rest} />
}
```

**Comment by danoc** [comment]
> I mean you should call `onClick` with the `event` which is what happens on regular buttons

> the component should also allow to pass `onKeyPress` which will fire both `onKeyPress` and `onClick`.
> Something like this:
> 
> ```js-jsx
> onKeyPress = event => {
>    const { onKeyPress, onClick } = this.props
>    typeof onKeyPress == 'function' && onKeyPress(event)
>    typeof onClick == 'function' && ['Enter', 'Space'].includes(event.key) && onClick(event)
> }
> 
> render() {
>   const { onClick, onKeyPress, ...rest } = this.props
>   return <Component onClick={onClick} onKeyPress={this.onKeyPress} {...rest} />
> }
> ```

Ah, great points. 

If anyone is interested, I'd be happy to accept a PR for both of these. (If not I'll get to this tonight.)

**Comment by danoc** [comment]
@giuseppeg — Thanks for the tip. Just merged and will release as `0.1.1`.

**Comment by giuseppeg** [comment]
@danoc great! Sorry I am based in EU and it was already night for me when I wrote :) Cool project btw!

One more thing, I think (you should verify this) that if the user calls `event.preventDefault()` in their `onKeyPress` then `onClick` won't fire.. in that case you should shortcircuit:

```diff
   // Run user supplied `onKeyPress` first if there is one
    if (typeof onKeyPress === "function") {
      onKeyPress(event);
+      if (event.isDefaultPrevented()) {
+         return
+     }
    }
     switch (event.key) {
      case "Space":
```

**Comment by danoc** [comment]
Good idea and glad you like it! I'll re-open this and test that.

**Comment by danoc** [comment]
Ok, I'm convinced. PR is ready for another look if you'd like: #10.

**Comment by danoc** [comment]
PR was merged. 🎉
